### ISSUE TITLE
Depreication warnings.

### ISSUE THREAD

**Issue by ipleten** [ghoneycutt/puppet-module-nscd#49]
Hi there,
```

Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/nscd/manifests/init.pp", 257]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 4]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/nscd/manifests/init.pp", 259]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 4]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/nscd/manifests/init.pp", 260]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 4]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/etc/puppetlabs/code/modules/nscd/manifests/init.pp", 267]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 4]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/nscd/manifests/init.pp", 272]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 4]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Bool instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/etc/puppetlabs/code/modules/nscd/manifests/init.pp", 622]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 4]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/datadog_agent/manifests/init.pp", 236]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 6]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Integer. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/modules/datadog_agent/manifests/init.pp", 246]:["/etc/puppetlabs/code/modules/roles/manifests/test.pp", 6]
   (at /etc/puppetlabs/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')

```

puppet 4.8.0
puppetlabs-stdlib v4.14.0
ghoneycutt-nscd (v1.9.1)

**Comment by ghoneycutt** [comment]
Thank you for reporting this. The module is currently backward compatible with Puppet v3, which is why you see the deprecation warnings. Since Puppet 3 is EOL and this module is feature complete, I will be moving to release a new major version that drops compatibility for Puppet 3. In the meantime, these warnings are just warnings :)
